### ISSUE TITLE
indexのキャスト一覧のデータについて

### ISSUE THREAD

**Issue by 0505Keitan** [hrqsn/ImaginationServer#2]
index.vueのキャスト一覧がJSONがそのまま書いてあってちょっと読みにくかったので、[@/static/casts.json](https://github.com/hrqsn/ImaginationServer/blob/master/static/casts.json)のデータにマージしてJSONから読み込めるようにしたほうがいいかもしれません。

(もう実装済みですぐPR出せるなんて言えない)

**Comment by hrqsn** [comment]
ありがとう！
プルリクお願いします
