### ISSUE TITLE
Social Iconの大きさと間隔

### ISSUE THREAD

**Issue by 0505Keitan** [hrqsn/ImaginationServer#6]
若干各Social Iconが小さめで押しにくいかと思います。
また、Social Iconの拡大に伴って`margin-right`を24px -> 30pxにしたほうがいいかもしれません。

# サイズ
 - PC - 16px
![image](https://user-images.githubusercontent.com/24855244/88145623-af069a80-cc35-11ea-9525-06306033c6c9.png)
 - Mobile (iPhoneX / XS) - 16px
![image](https://user-images.githubusercontent.com/24855244/88145713-d2314a00-cc35-11ea-980a-341b67d4449a.png)

25pxが見やすいかなと思います(要調整)
 - PC - 25px
![image](https://user-images.githubusercontent.com/24855244/88152090-7fa85b80-cc3e-11ea-8da8-8abb476b48c8.png)
 - Mobile (iPhoneX / XS) - 25px
![image](https://user-images.githubusercontent.com/24855244/88152156-9b136680-cc3e-11ea-81df-322065430fc9.png)

# margin
 - 24px
![image](https://user-images.githubusercontent.com/24855244/88152711-6358ee80-cc3f-11ea-8ad4-4003f8557f8f.png)
 - 30px
![image](https://user-images.githubusercontent.com/24855244/88152650-4ae8d400-cc3f-11ea-921f-eccb9af1b9d7.png)

**Comment by hrqsn** [comment]
ありがとう！
今のところそこまで小さいと思わないので保留します。ただスマホの方は若干小さめかもしれないので、変えるかもです。助かります！👍
